promotion_index:
    path:     /
    defaults: { _controller: "FormationBundle:Promotion:index" }
    methods:  GET

promotion_show:
    path:     /{id}/show
    defaults: { _controller: "FormationBundle:Promotion:show" }
    methods:  GET

promotion_new:
    path:     /new
    defaults: { _controller: "FormationBundle:Promotion:new" }
    methods:  [GET, POST]

promotion_edit:
    path:     /{id}/edit
    defaults: { _controller: "FormationBundle:Promotion:edit" }
    methods:  [GET, POST]

promotion_delete:
    path:     /{id}/delete
    defaults: { _controller: "FormationBundle:Promotion:delete" }
    methods:  DELETE
